### ISSUE TITLE
add subject functionality

### ISSUE THREAD

**Issue by Refaelbenzvi24** [flashcards-app/frontend#23]
Allowing users to add subjects from the UI.

if anyone wants to take it on themself please let me know here and I'll explain more if needed.

**Comment by IdLevi1705** [comment]
I can take it

**Comment by Refaelbenzvi24** [comment]
> I can take it

great!

Let me know if you need anything from me...

**Comment by Refaelbenzvi24** [comment]
Added the functionality to the "addQuestions" page on the select input.
